/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HardwareAssemblyRouteImport } from './routes/hardware-assembly'
import { Route as PerceptionRouteImport } from './routes/perception'
import { Route as SimulatorRouteImport } from './routes/simulator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HardwareAssemblyRoute = HardwareAssemblyRouteImport.update({
  id: '/hardware-assembly',
  path: '/hardware-assembly',
  getParentRoute: () => rootRouteImport,
} as any)
const PerceptionRoute = PerceptionRouteImport.update({
  id: '/perception',
  path: '/perception',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hardware-assembly': typeof HardwareAssemblyRoute
  '/perception': typeof PerceptionRoute
  '/simulator': typeof SimulatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hardware-assembly': typeof HardwareAssemblyRoute
  '/perception': typeof PerceptionRoute
  '/simulator': typeof SimulatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hardware-assembly': typeof HardwareAssemblyRoute
  '/perception': typeof PerceptionRoute
  '/simulator': typeof SimulatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hardware-assembly' | '/perception' | '/simulator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hardware-assembly' | '/perception' | '/simulator'
  id: '__root__' | '/' | '/hardware-assembly' | '/perception' | '/simulator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HardwareAssemblyRoute: typeof HardwareAssemblyRoute
  PerceptionRoute: typeof PerceptionRoute
  SimulatorRoute: typeof SimulatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardware-assembly': {
      id: '/hardware-assembly'
      path: '/hardware-assembly'
      fullPath: '/hardware-assembly'
      preLoaderRoute: typeof HardwareAssemblyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perception': {
      id: '/perception'
      path: '/perception'
      fullPath: '/perception'
      preLoaderRoute: typeof PerceptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HardwareAssemblyRoute: HardwareAssemblyRoute,
  PerceptionRoute: PerceptionRoute,
  SimulatorRoute: SimulatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
